FROM quay.io/konflux_ui_qe/konflux-ui-tests-base:5.8.0

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN wget "https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-amd64" && \
    mv cosign-linux-amd64 /usr/local/bin/cosign && \
    chmod +x /usr/local/bin/cosign

USER node:0

COPY @types /tmp/@types
COPY public /tmp/public
COPY src /tmp/src
COPY package.json /tmp/package.json
COPY tsconfig.json /tmp/tsconfig.json
COPY webpack.config.js /tmp/webpack.config.js
COPY webpack.instrumented.config.js /tmp/webpack.instrumented.config.js
COPY webpack.prod.config.js /tmp/webpack.prod.config.js
COPY yarn.lock /tmp/yarn.lock
COPY aliases.config.js /tmp/aliases.config.js
COPY --chown=node:root --chmod=775 e2e-tests /tmp/e2e
RUN chmod -R 775 /tmp/e2e

RUN cd /tmp/ && \
    npm i yarn --f

RUN cd /tmp/e2e && \
    umask 0002 && \
    npm i && \
    node_modules/.bin/cypress install && \
    mkdir -p /tmp/artifacts && \
    chmod -R a+rwx /tmp/artifacts ${CYPRESS_CACHE_FOLDER}

WORKDIR /tmp/
COPY --chown=node:root --chmod=775 e2e-tests/entrypoint.sh /tmp/

ENTRYPOINT ["/tmp/entrypoint.sh"]
CMD [""]
