FROM quay.io/konflux_ui_qe/konflux-ui-tests-base:5.8.0

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN wget "https://github.com/sigstore/cosign/releases/download/v2.4.0/cosign-linux-amd64" && \
    mv cosign-linux-amd64 /usr/local/bin/cosign && \
    chmod +x /usr/local/bin/cosign

FROM node:lts-alpine
# WORKDIR /tmp/

RUN echo "List"
RUN ls -la tmp

USER node:0
COPY --chown=node:root --chmod=775 . /tmp/
COPY --chown=node:root --chmod=775 e2e-tests /tmp/e2e

RUN ls -la
RUN ls -la tmp

RUN cd tmp/e2e && \
    umask 0002 && \
    npm i && \
    node_modules/.bin/cypress install && \
    mkdir -p tmp/artifacts && \
    chmod -R a+rwx /tmp/artifacts ${CYPRESS_CACHE_FOLDER}

WORKDIR /tmp/
COPY --chown=node:root --chmod=775 e2e-tests/entrypoint.sh /tmp/

ENTRYPOINT ["/tmp/entrypoint.sh"]
CMD [""]
