---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-main-pipeline
  namespace: mtakac-tenant
spec:
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: konflux-test-infra-secret
      description: The name of secret where testing infrastructures credentials are stored.
      type: string
      default: konflux-test-infra
    - name: oci-container-repo
      default: 'quay.io/mtakac-tenant/konflux-ui-test'
      description: The ORAS container used to store all test artifacts.
    - name: artifact-browser-url
      description: 'URL to the artifact browser deployment. If provided, a link will be added to PR comments.'
      default: ''
      type: string
  tasks:
    - name: run-local
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/milantaky/konflux-ui-test
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/Tasks/run-local.yaml

    - name: test-image
      runAfter:
        - run-local
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/milantaky/konflux-ui-test
          - name: revision
            value: main
          - name: pathInRepo
            value: integration-tests/Tasks/run-e2e-konflux-ui-skipped.yaml
      params:
        # - name: test-image
        #   value: '$(tasks.run-local.results.test-image)'
        - name: test-image
          value: quay.io/mtakac-tenant/konflux-ui-test:pr-53